### ISSUE TITLE
EnterでもSubmitする

### ISSUE THREAD

**Issue by solufa** [deus-app/deus-creatio#49]
入力後にボタン押すのが面倒すぎる
InputとButtonをformタグで囲ってonSubmitでsendするとか
![image](https://github.com/deus-app/deus-creatio/assets/9402912/4d939970-1fef-4309-824d-ff591e933bf7)

**Comment by s1f102100793** [comment]
textareaにおけるonSubmitの条件が複雑なためクローズ
